---
name: Specs Rails 7.0

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: ['2.7', '3.0', '3.1', '3.2']

    env:
      RAILS: '7.0'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Prepare database
        env:
          RAILS_ENV: test
        run: bin/rails db:test:prepare

      - name: Run tests
        run: bin/rspec --profile
