---
name: Specs Rails 7.1

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: ['2.7', '3.0', '3.1', '3.2']

    env:
      RAILS_ENV: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Prepare database
        run: bin/rails db:test:prepare

      - name: Bundle install
        run: bin/appraisal rails-71 bundle install

      - name: Run tests
        run: bin/appraisal rails-71 rspec --profile
